---

- name: "Remove any recovery.done files."
  ansible.builtin.file:
    state: absent
    path: "{{pg_replication_postgresql_path}}/{{pg_replication_postgresql_data_dir}}/recovery.done"

- name: "Remove any trigger files."
  ansible.builtin.file:
    state: absent
    path: "{{pg_replication_trigger_file}}"
